// constants.js

export const utilityTexts = [
    "", 
    "",
    "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // "",
    // "", 
    // ""
]

export const pickTexts = [
    // "Pick 1\n(轉盤)",
    // "Pick 4\n(轉盤)",
    // "Pick 5\n(自選)",
    // "Pick 8\n(自選)",
    "Pick 1",
    "Pick 4",
    "Pick 5",
    "Pick 8",
    "Pick 9",
    "Pick 12",
    "Pick 13",
    "Pick 16",
    "Pick 18",
    "Pick 19",
    "Pick 22",
    "Pick 23",
    "Pick 26",
    "Pick 27",
    "Pick 30",
    "Pick 31",
    "Pick 17",
    "Pick 20",
    "Pick 21",
    "Pick 24",
    "Pick 25",
    "Pick 28",
    "Pick 29",
    "Pick 32",
    // "Pick 2\n(轉盤)",
    // "Pick 3\n(轉盤)",
    // "Pick 6\n(自選)",
    // "Pick 7\n(自選)",
    "Pick 2",
    "Pick 3",
    "Pick 6",
    "Pick 7",
    "Pick 10",
    "Pick 11",
    "Pick 14",
    "Pick 15"
]

export const banTexts = [
    // "Ban 16", 
    // "Ban 14", 
    // "Ban 12", 
    // "Ban 9", 
    // "Cond 8", 
    // "Cond 6", 
    // "Cond 3",
    // "Cond 1",
    // "Cond 2",
    // "Cond 4",
    // "Cond 5", 
    // "Cond 7", 
    // "Ban 8", 
    "Ban 6", 
    "Ban 3",
    "Ban 1",
    "Ban 2",
    "Ban 4",
    "Ban 5", 
    // "Ban 7", 
    // "Ban 10", 
    // "Ban 11", 
    // "Ban 13", 
    // "Ban 15"
]