// src/modules/shared/infrastructure/imageRegistry.ts

import type { Weapon, Element } from '@shared/contracts/character/value-types';
import type { ElementImageKey, WeaponImageKey, ProfileImageKey, WishImageKey } from './imageRegistry.manifest';

const profileImages = import.meta.glob('@/assets/images/profile/*.webp', {
    eager: true,
    import: 'default',
});

const wishImages = import.meta.glob('@/assets/images/wish/*.png', {
    eager: true,
    import: 'default',
});

const elementImages = import.meta.glob('@/assets/images/element/*.svg', {
    eager: true,
    import: 'default',
});

const weaponImages = import.meta.glob('@/assets/images/weapon/*.webp', {
    eager: true,
    import: 'default',
});

export function getProfileImagePath(characterKey: string): string | undefined {
    const key = `/src/assets/images/profile/${toPascalCase(characterKey)}_Profile.webp`;
    return profileImages[key] as string | undefined;
}

export function getWishImagePath(characterKey: string): string | undefined {
    const key = `/src/assets/images/wish/${toPascalCase(characterKey)}_Wish.png`;
    return wishImages[key] as string | undefined;
}

export function getElementImagePath(element: Element): string | undefined {
    const key = `/src/assets/images/element/${element}_White.svg`;
    return elementImages[key] as string | undefined;
}

export function getWeaponImagePath(weapon: Weapon): string | undefined {
    const key = `/src/assets/images/weapon/${weapon}.webp`;
    return weaponImages[key] as string | undefined;
}

function toPascalCase(key: string): string {
    return key
        .split('_')
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join('');
}

// ── Compile-time asset coverage (manifest is regenerated by `npm run gen:images`) ──
// Each alias errors if the left set is not fully covered by the right one — i.e. an
// enum member or a character is missing its image file. This is the whole point of
// codegen over a raw glob: a missing asset becomes a type error, not a silent undefined.
type AssertCoveredBy<_Subset extends _Superset, _Superset> = true;

// Every Element (except None, which has no icon) must have an element/*_White.svg.
type _ElementCoverage = AssertCoveredBy<Exclude<Element, Element.None>, ElementImageKey>;
// Every Weapon must have a weapon/*.webp.
type _WeaponCoverage = AssertCoveredBy<Weapon, WeaponImageKey>;
// profile/ and wish/ must stay 1:1 — a character added to one but not the other errors.
type _ProfileHasWish = AssertCoveredBy<ProfileImageKey, WishImageKey>;
type _WishHasProfile = AssertCoveredBy<WishImageKey, ProfileImageKey>;
